language: go
go:
    - 1.14.1
install:
    - go get -d -v ./...
script:
    - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
    - bash <(curl -s https://codecov.io/bash)
